# Form implementation generated from reading ui file 'd:\PRO\CODE\Formation_OpenClassrooms\P4\views\qt_ux\players.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_players(object):
    def setupUi(self, players):
        players.setObjectName("players")
        players.resize(469, 463)
        self.centralwidget = QtWidgets.QWidget(players)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Player = QtWidgets.QLabel(self.centralwidget)
        self.Player.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Player.sizePolicy().hasHeightForWidth())
        self.Player.setSizePolicy(sizePolicy)
        self.Player.setMinimumSize(QtCore.QSize(0, 120))
        self.Player.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(22)
        self.Player.setFont(font)
        self.Player.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Player.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Player.setObjectName("Player")
        self.verticalLayout.addWidget(self.Player)
        self.AddPlayer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddPlayer.sizePolicy().hasHeightForWidth())
        self.AddPlayer.setSizePolicy(sizePolicy)
        self.AddPlayer.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Light")
        font.setPointSize(18)
        self.AddPlayer.setFont(font)
        self.AddPlayer.setObjectName("AddPlayer")
        self.verticalLayout.addWidget(self.AddPlayer)
        self.ListPlayers = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListPlayers.sizePolicy().hasHeightForWidth())
        self.ListPlayers.setSizePolicy(sizePolicy)
        self.ListPlayers.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Light")
        font.setPointSize(18)
        self.ListPlayers.setFont(font)
        self.ListPlayers.setFlat(False)
        self.ListPlayers.setObjectName("ListPlayers")
        self.verticalLayout.addWidget(self.ListPlayers)
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Light")
        font.setPointSize(16)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        self.verticalLayout.addWidget(self.Back)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        players.setCentralWidget(self.centralwidget)

        self.retranslateUi(players)
        QtCore.QMetaObject.connectSlotsByName(players)

    def retranslateUi(self, players):
        _translate = QtCore.QCoreApplication.translate
        players.setWindowTitle(_translate("players", "MainWindow"))
        self.Player.setText(_translate("players", "Joueurs"))
        self.AddPlayer.setText(_translate("players", "Ajouter un joueur"))
        self.ListPlayers.setText(_translate("players", "Voir ou modifier le score des joueurs"))
        self.Back.setText(_translate("players", "Retour"))
