QUIT = 0
BACK = 0

# validation
YES = 1
NO = 2

# main window
PLAYERS = 1
TOURNAMENT = 2

# player window
ADD_PLAYER = 1
SEE_PLAYER = 2

# tournament window
NEW_TOURNAMENT = 1
RETRIEVE_TOURNAMENT = 2
REPORT = 3

# report window
REPORT_PLAYERS = 1
REPORT_TOURNAMENT = 2

# player report window
RP_ALL_PLAYERS_ALPHABETIC = 1
RP_ALL_PLAYERS_RANK = 2
RP_ALL_PLAYERS_T_ALPHABETIC = 3
RP_ALL_PLAYERS_T_RANK = 4

# tournament report window
RT_ALL_IR = 1
RT_ALL_ROUND = 2

# existant tournament found
ERASE_LAST_FOUND_TOURNAMENT = 1
BACK_ERASE_LAST_FOUND_TOURNAMENT = 2